1:
  objective: regression
  metric: rmse
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 1000
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10
